
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - logging.yo.logsync
  resources:
  - logsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.yo.logsync
  resources:
  - logsyncs/finalizers
  verbs:
  - update
- apiGroups:
  - logging.yo.logsync
  resources:
  - logsyncs/status
  verbs:
  - get
  - patch
  - update
